### ISSUE TITLE
MoveToVirtual doesn't work for me or i got it wrong

### ISSUE THREAD

**Issue by DonoDayZ** [MediatedCommunications/WindowsInput#10]
private void button1_Click_1(object sender, EventArgs e)
  {
       WindowsInput.Simulate.Events().MoveToVirtual(10,10).Click().Invoke();
  }

MoveToVirtual: it would be moving the cursor to some position without using my cursor, but it is moving my cursor.
I would like to know how do I go to a position without moving the cursor.

**Comment by TonyValenti** [comment]
@DonoDayZ - I'm not sure what you mean.  I'm not sure it is possible to move your cursor to a position without... moving your cursor to that position.

Can you give an example of what you want?

**Comment by DonoDayZ** [comment]
I was using SendMessage, to click on a certain position without moving my mouse.
However, this only works on windows.
Then a friend told me he was using his WindowsInput, but I can't do this by clicking on a position without moving my mouse.

**Comment by TonyValenti** [comment]
Oh!  I know what you're mean now. 

No.  This package will not do that.

Windows has multiple "layers" in which input is processed. This package operates at the lowest layer by directly injecting data into the input buffer.
