### ISSUE TITLE
Get mouse cursor position API

### ISSUE THREAD

**Issue by arphox** [MediatedCommunications/WindowsInput#16]
Hi!

I'm trying to use the nuget package to simply get the current position of the cursor.
Can I do that? If yes, how?

I was trying `WindowsInput.Capture.Global.Mouse()...` but only events are there, while I need simple getter method.

**Comment by TonyValenti** [comment]
Hi @arphox !  I'm so sorry!  I never saw this message.  In my next update, I'll include a ```Snapshot.Mouse()``` method that will do exactly this.
