### ISSUE TITLE
Cant use the input

### ISSUE THREAD

**Issue by ghost** [MediatedCommunications/WindowsInput#21]
Ive downloaded the package with windowsinput but whenever i try to use it it just says "The type or namespace name 'WindowsInput' could not be found (are you missing a using directive or an assembly reference?)"

**Comment by Kristoffeh** [comment]
I started using it a few days ago and works like a charm for me. From the looks of it, you may have forgotten to add the asssembly reference.

You need `using WindowsInput;`

If you already had that, then you need to right click on your Project => Add => Project Reference and find your file =D
