### ISSUE TITLE
CurrentThreadKeyboardEventSource cause "Arithmetic operation resulted in an overflow"

### ISSUE THREAD

**Issue by zhuxb711** [MediatedCommunications/WindowsInput#25]
Arithmetic operation resulted in an overflow.
![image](https://user-images.githubusercontent.com/42038175/229367222-a4f8ef67-fddc-4158-a58a-291f778b16f1.png)

**Comment by zhuxb711** [comment]
Should be here: https://github.com/MediatedCommunications/WindowsInput/blob/9738dd33b298799374fc00bfb462f135c3f13e41/WindowsInput/EventsSources/Keyboard/CurrentThreadKeyboardEventSource.cs#L32

**Comment by TonyValenti** [comment]
What are you pressing to make that happen?

**Comment by zhuxb711** [comment]
I pressed "D" in this scenario. It seems that every key will cause this issue. 

Tip: I tested it in Windows App Sdk

**Comment by TonyValenti** [comment]
Can you give me a link to a GitHub repository that I can use to test?    I haven't used it with that SDK in the past.

**Comment by zhuxb711** [comment]
Demo for you, thanks!
[KeyboardTest.zip](https://github.com/MediatedCommunications/WindowsInput/files/11134187/KeyboardTest.zip)

**Comment by TonyValenti** [comment]
Thanks.  The current thread hook is seldom used and it looks like there was a nuance with it.  I've just published an update.

**Comment by zhuxb711** [comment]
Thanks, it's really fast to fix this issue. Very appreciate!

Besides I want to know what is the difference between KeyboardAsync() and Keyword()? Only Global hook have the KeyboardAsync().

**Comment by TonyValenti** [comment]
It has been a long time since I wrote that code, but I believe the ASYNC version basically runs in its own thread.
