### ISSUE TITLE
Drag and Drop 

### ISSUE THREAD

**Issue by 11t11** [MediatedCommunications/WindowsInput#4]
Hi,
I hope this message find you healthy and clear of Corrona
I want to know if there is an option to drag and drop a file or file path (or collection) selected to a destination / application window (using the application name) or other destination input. I would appreciate a code sample.

Thanks

**Comment by TonyValenti** [comment]
Hi @11t11 - I think you might misunderstand what this library does.  This is a low-level library that lets you intercept and simulate mouse and keyboard events.  Using this library, you can simulate moving the mouse to a certain location, holding down the mouse, moving it to another location, and releasing it (all the parts of a drag and drop operation), however, it is up to you to be able to determine what those locations should be.
