### ISSUE TITLE
Random keystrokes

### ISSUE THREAD

**Issue by C1rdec** [MediatedCommunications/WindowsInput#8]
Some of my users are experiencing random keystrokes after my application is running for a good amount of times.
*(A restart of the application fix the issue)*

Here's how I handle the `EventBuilder`

```
protected async Task SendCommand(string command, bool setForegound = true)
{
	var eventBuilder = Simulate.Events();
	eventBuilder.Click(KeyCode.Return);
	eventBuilder.ClickChord(KeyCode.LControl, KeyCode.A);
	eventBuilder.Click(command);
	eventBuilder.Click(KeyCode.Return);

	if (setForegound)
	{
		// This is to fix the first SetForegroundWindow
		await Simulate.Events().Click(KeyCode.LMenu).Invoke();
		Native.SetForegroundWindow(this._windowHandle);
		await Task.Delay(10);
		var foregroundWindow = Native.GetForegroundWindow();
		if (this._windowHandle != foregroundWindow)
		{
			await Task.Delay(100);
		}
	}

	await eventBuilder.Invoke();
}
```

**Is there anything I need to dispose?**

**Comment by TonyValenti** [comment]
@C1rdec 
This looks good.  When you're siumulating events, there is not thing you need to dispose of.

What does your app do and what is the nature of the key strokes that are randomly happening??

**Comment by C1rdec** [comment]
My app is a Path of Exile overlay I've been using your older Library but I came across a Github Issue that was pointing here since you make a complete rewrite. *([Poe Lurker](https://github.com/C1rdec/Poe-Lurker))*

Basically as an example the user wanted to write "Thanks" and here is the resulting string.

![image](https://user-images.githubusercontent.com/5436436/94955405-8104c880-04b8-11eb-80b5-ca566c6c7dee.png)

**Comment by TonyValenti** [comment]
Because EventBuilder is basically just a list, it doesn't actually do anything until you Invoke() it and I'm sure that what your'e doing is fine.

Have you been able to replicate the issue?  Can you share a video of it happening?

Are you just using EventBuilder or are you using a keyboard listening functions as well?

**Comment by C1rdec** [comment]
Sorry for the delay...
I'm just using only the EventBuilder I will try to get you a video but basically I think there's multiple command that fire at the same times I think the issue might be on my side since I was not awaiting the call all the way up. 

Here is the corresponding issue: 
https://github.com/C1rdec/Poe-Lurker/issues/211

I'll keep you updated if the issue still occurs.

**Comment by C1rdec** [comment]
The issue was on my side.
